<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class ProjectReport extends Model
{
    use HasFactory;

    protected $fillable = [
        'project_id',
        'report_type',
        'file_name',
        'file_path',
        'file_size',
        'mime_type',
        'generated_by',
        'generated_at',
        'download_count',
        'report_data',
    ];

    protected $casts = [
        'generated_at' => 'datetime',
        'report_data' => 'array',
        'download_count' => 'integer',
    ];

    // ==============================================
    // RELATIONSHIPS
    // ==============================================

    /**
     * Project report belongs to a project
     */
    public function project(): BelongsTo
    {
        return $this->belongsTo(Project::class);
    }

    /**
     * Report was generated by an employee
     */
    public function generatedBy(): BelongsTo
    {
        return $this->belongsTo(Employee::class, 'generated_by');
    }

    // ==============================================
    // HELPER METHODS
    // ==============================================

    /**
     * Get formatted file size
     */
    public function getFormattedSizeAttribute(): string
    {
        $bytes = $this->file_size;
        $units = ['B', 'KB', 'MB', 'GB'];
        $i = 0;

        while ($bytes >= 1024 && $i < count($units) - 1) {
            $bytes /= 1024;
            $i++;
        }

        return round($bytes, 2) . ' ' . $units[$i];
    }

    /**
     * Increment download count
     */
    public function incrementDownloads(): void
    {
        $this->increment('download_count');
    }
}
